export const words = {
    en: [
        "a", "again", "all", "also", "and", "another", "any", "around",
        "as", "ask", "at", "back", "because", "become", "before",
        "begin", "both", "but", "by", "call", "can", "change", "child",
        "come", "could", "course", "day", "develop", "each", "early",
        "end", "even", "eye", "face", "fact", "few", "first", "follow",
        "from", "general", "get", "give", "good", "govern", "group",
        "hand", "have", "he", "head", "help", "here", "high", "hold",
        "home", "how", "however", "if", "increase", "interest", "it",
        "know", "large", "last", "lead", "leave", "life", "like",
        "line", "little", "look", "make", "man", "may", "mean", "might",
        "more", "must", "need", "never", "new", "no", "now", "number",
        "of", "off", "old", "on", "one", "open", "or", "order", "out",
        "over", "own", "part", "people", "person", "place", "plan",
        "play", "point", "possible", "present", "problem", "program",
        "public", "real", "right", "run", "say", "see", "seem", "show",
        "small", "some", "stand", "state", "still", "such", "system",
        "take", "than", "that", "the", "then", "there", "these", "they",
        "thing", "think", "this", "those", "time", "to", "under", "up",
        "use", "very", "way", "what", "when", "where", "while", "will",
        "with", "without", "work", "world", "would", "write", "you",
        "she", "set", "we", "long", "in", "many", "do", "after", "which",
        "so", "same", "other", "house", "during", "much", "just", "consider",
        "since", "should", "only", "tell", "about"
    ],
    es: [
        "amor", "cielo", "luz", "sol", "noche", "día", "flor", "vida", "risa", "sueño",
        "camino", "esperanza", "fuerza", "fuego", "agua", "tierra", "aire", "paz", "guerra", "niño",
        "madre", "padre", "hermano", "hermana", "familia", "amigo", "juego", "rayo", "trueno", "lluvia",
        "mar", "ola", "playa", "arena", "montaña", "valle", "bosque", "río", "lago", "nube",
        "estrella", "universo", "planeta", "pelo", "azul", "verde", "rojo", "blanco", "negro", "gris",
        "rosa", "morado", "amarillo", "color", "pintura", "arte", "música", "sonido", "voz", "palabra",
        "verso", "poema", "libro", "cuento", "historia", "aventura", "viaje", "caminar", "correr", "volar",
        "nadar", "saltó", "brincó", "gritó", "cantó", "bailó", "miró", "tocó", "oyó", "pensó",
        "soñó", "creó", "construyó", "rompió", "abrió", "cerró", "subió", "bajó", "entró", "salió",
        "comió", "bebió", "vivió", "murió", "amó", "odió", "lloró", "reí", "habló", "calló",
        "escuchó", "escribió", "leyó", "dibujó", "jugó", "trabajó", "descansó", "durmió", "despertó", "pensamiento",
        "idea", "mente", "cuerpo", "alma", "espíritu", "corazón", "sangre", "piel", "ojos", "boca",
        "nariz", "oído", "mano", "pie", "cabeza", "hombro", "brazo", "pierna", "espalda", "pecho",
        "animal", "perro", "gato", "pájaro", "pez", "caballo", "vaca", "oveja", "lobo", "tigre",
        "león", "zorro", "conejo", "ratón", "jirafa", "elefante", "mono", "oso", "cabra", "cerdo",
        "águila", "serpiente", "rana", "mariposa", "abeja", "hormiga", "libélula", "grillo", "mosca", "pulga",
        "escarabajo", "vuelo", "noche", "aurora", "ocaso", "mañana", "tarde", "mediodía", "sombra", "claridad",
        "eco", "silencio", "brisa", "tormenta", "huracán"
    ],
    fr: [
        "amour", "jour", "nuit", "soleil", "lune", "étoile", "ciel", "terre", "feu", "eau",
        "air", "vent", "pluie", "neige", "orage", "nuage", "montagne", "vallée", "forêt", "rivière",
        "lac", "mer", "océan", "plage", "sable", "pierre", "fleur", "arbre", "feuille", "racine",
        "branche", "fruit", "pomme", "poire", "raisin", "banane", "orange", "citron", "fraise", "cerise",
        "chien", "chat", "oiseau", "poisson", "cheval", "vache", "mouton", "cochon", "loup", "renard",
        "souris", "lapin", "ours", "tigre", "lion", "éléphant", "girafe", "serpent", "grenouille", "abeille",
        "fourmi", "mouche", "papillon", "escargot", "araignée", "libellule", "corps", "tête", "main", "pied",
        "jambe", "bras", "épaule", "dos", "ventre", "cœur", "esprit", "âme", "voix", "parole",
        "pensée", "idée", "rêve", "espoir", "peur", "colère", "joie", "tristesse", "amitié", "famille",
        "mère", "père", "frère", "sœur", "enfant", "bébé", "homme", "femme", "garçon", "fille",
        "ami", "amie", "professeur", "élève", "école", "maison", "chambre", "salon", "cuisine", "jardin",
        "ville", "village", "rue", "route", "voiture", "vélo", "train", "avion", "bateau", "bus",
        "temps", "minute", "heure", "jour", "semaine", "mois", "année", "matin", "soir", "midi",
        "minuit", "printemps", "été", "automne", "hiver", "chaud", "froid", "clair", "sombre", "beau",
        "laid", "petit", "grand", "jeune", "vieux", "nouveau", "ancien", "bon", "mauvais", "gentil",
        "méchant", "fort", "faible", "rapide", "lent", "heureux", "triste", "fatigué", "malade", "vivant",
        "mort", "parler", "écouter", "voir", "regarder", "toucher", "marcher", "courir", "sauter", "voler",
        "dormir", "manger", "boire", "aimer", "détester", "travailler", "jouer", "chanter", "danser", "écrire",
        "lire", "ouvrir", "fermer", "entrer", "sortir", "monter", "descendre", "tomber", "rester", "partir",
        "venir", "aller", "faire", "être", "avoir", "pouvoir"
    ]
}